### ISSUE TITLE
Pas de chance

### ISSUE THREAD

**Issue by manland** [cheleb/test-stream-wisdom#1]
Il manque un s au titre de ton repo :name_badge: :smiling_imp: !

**Comment by cheleb** [comment]
Mais ... Tu m'espionne ?

√olivier/mobile

**Comment by cheleb** [comment]
Anyway thx :p

**Comment by manland** [comment]
Hahaha non je ne t'espionne pas, j'utilise skimbo qui à un espèce de twitter de github ^^

![selection_086](https://cloud.githubusercontent.com/assets/1492516/8053310/a8c6b7cc-0e8f-11e5-9692-b77770d1a993.png)
